#Autor pluginu: Saimonovski
# Config do gemów

config-version: 2

#dane logowania do bazy danych, jesli nie uda polaczyc sie z baza danych zostanie uzyta baza lokalna
database:
  use-mysql: false #czy uzywac mysql czy bazy danych flat
  host: 192.168.1.1
  databse-name: "nazwa_bazy"
  user-name: "root"
  password: "password"
  port: 3306

#  #komendy
# dla graczy:
# /gemy
# /gemshop
# dla administracji:
# /agemy (add/set/remove) (nick/all) (ilosc)

#placeholdery:
# %gem_balance% - balans ilosci vpln w portfelu

#Permisje:
# svm.portfel.admin - dostep do komend administratora

 #material do wypelnienia na tlo

currency-symbol: "vPLN"
#konfiguracja glownego gui
main-gui:
  title-gui: "<bold><white> Sklep </white></bold>"
  size: 9
  fill-material: "YELLOW_STAINED_GLASS_PANE"

#konfiguracja przedmiotu do zamykania menu. Widoczny w glownym menu
exit-button:
  slot: 0
  display-name: "<red><bold>Zamknij</bold></red>"
  lore:
    - "<white>Kliknij aby zamknac</white>"
  enchant-glow: true

  #konfiguracja przedmiotu do powrotu do glownego menu. Widoczny w menu kategorii
return-button:
  slot: 0
  display-name: "<red><bold>Powrot</bold></red>"
  lore:
    - "<white>Kliknij aby powrocic do glownego menu</white>"

categories:
  category_id:
    title-gui: "<red><bold>Testowa katefgoria</bold></red>"
    display-name: "<red><bold> Kategoria produktow </bold></red>"
    material: "DIAMOND"
    lore:
      - "<white> Kliknij aby zobaczyc produkty </white>"
    slot: 6 #slot w ktorym bedzie widoczna kategoria
    enchant-glow: true #czy powinien byc glow taki jak maja enchantowane itemki
    model-data: -1 #custom model data przedmiotu. Daj na -1 aby wylaczyc
    fill-material: "BLACK_STAINED_GLASS_PANE" #material jakim powinno zostac wypelnione gui po otwarciu kategori
    size: 9 #rozmiar gui, musi byc wielokrotnoscia 9 !
    #Lista przedmiotow znajdujacych sie w kategorii (do zakupu, konfiguracja przedmiotow ponizej)
    #Jesli lista jest pusta lub zakomentowana nie otworzy sie zadn gui z przedmiotami
    contains-items:
      item_id: 4 #klucz czyli item_id to jest id przedmiotu a liczba to slot w ktorym ma sie pojawic

  information:
    title-gui: ""
    display-name: "<red><bold> Witaj w portfelu </bold></red>"
    material: "STONE"
    lore:
      - "<white> Witaj %player_name% </white>"
      - "<white> Twoj stan konta wynosi: %portfel_balance% </white>"
    slot: 8
    enchant-glow: true
    model-data: -1
    fill-material: "AIR"
    size: 27

confirm-gui:
  fill-material: "BLACK_STAINED_GLASS_PANE"
  title-gui: "<green>Potwierdz zakup rangi</green>"
  size: 9
  item-slot: 5 #slot na ktorym ma sie pojawic ranga do zakpu
  confirm-button:
    display-name: "<green>Potwierdz</green>"
    material: "GREEN_WOOL"
    lore:
      - "<white>Kliknij aby potwierdzic</white>"
    slot: 6
  cancel-button:
    display-name: "<red>Anuluj</red>"
    material: "RED_WOOL"
    lore:
      - "<red>Kliknij aby anulowac</red>"
    slot: 4
#  contains-items:  #po kliknieciu sie nic nie stanie poniewaz lista przedmiotow jest zakomentowana
#  item_id: 1
items:
  item_id:
    display-name: "<red><bold> Ranga Hej </bold></red>"
    material: "DIAMOND"
    itemAmount: 1 #amount przedmiotu
    lore:
      - "<white> Kliknij aby kupic range </white>"
    price: 10.0 #Cena przedmiotu
    enchant-glow: true #czy powinien byc glow taki jak maja enchantowane itemki
    model-data: -1 #custom model data przedmiotu. Daj na -1 aby wylaczyc
    #Lista komend do wykonania przez konsole
    # %player% - nazwa gracza

    commands:
      - "say %player% Zakupil range Hej"

daily-reward:
  display-name: "<gold><bold>DZienna nagroda</gold></bold>"
  material: "EMERALD"
  lore:
    - "<white> Kliknij aby wylosowac dienna nagrode</white>"
  min-amount: 0.1
  max-amount: 1.0
  model-data: -1
  slot: 3  #slot w ktoym ma sie pojawic


messages:
  daily-reward-message: #wysylane podczas odbierania dziennej nagrody
    type: ACTIONBAR #typ wiadomosci dostepne: TITLE, SUBTITLE, , CHAT, ACTIONBAR, DISABLED
    message: "<blue> Wylosowales %amount% pieniedzy"

  money-give: #wysylane podczas dostania pieniedzy za pomoca komendy
    type: CHAT #typ wiadomosci dostepne: TITLE, SUBTITLE, , CHAT, ACTIONBAR, DISABLED
    message: "<blue> Twoje konto zostalo doladowane kwota %amount% </blue>"

  money-remove:
    type: CHAT #typ wiadomosci dostepne: TITLE, SUBTITLE, , CHAT, ACTIONBAR, DISABLED
    message: "<green> Zaplacono  %amount% </green>"

  product-buy:
    type: CHAT #typ wiadomosci dostepne: TITLE, SUBTITLE, , CHAT, ACTIONBAR, DISABLED
    message: "<green> Zakupiles %item-name% </green>"

  not-enough-money:
    type: CHAT #typ wiadomosci dostepne: TITLE, SUBTITLE, , CHAT, ACTIONBAR, DISABLED
    message: "<red> Nie masz wystarczajaco pieniedzy. </red>"
  cooldown-message:
    type: CHAT #typ wiadomosci dostepne: TITLE, SUBTITLE, , CHAT, ACTIONBAR, DISABLED
    message: "<red> Odebrales juz dzisiaj nagrode </red>"
  cancelled-message:
    type: CHAT #typ wiadomosci dostepne: TITLE, SUBTITLE, , CHAT, ACTIONBAR, DISABLED
    message: "<red>Anulowano </red>"
  admin-balance-check:
    type: ACTIONBAR #typ wiadomosci dostepne: TITLE, SUBTITLE, , CHAT, ACTIONBAR, DISABLED
    message: "<blue>Gracz %player% posiada %gem_balance% gemów </blue>"





# Powered by saimverse, www.saimverse.pl